; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Dockie"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Bansia Labs"
#define MyAppExeName "Dockie.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{98341145-3502-45E1-AD8F-72C0D5D9D500}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; The app creates this mutex (backend.py) so a reinstall/update can close a
; running Dockie before replacing its files instead of failing on a lock.
AppMutex=Dockie
CloseApplications=yes
RestartApplications=no
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=dockie_setup_v101
SetupIconFile=D:\Projects\Automation\FileFinder\robot.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Projects\Automation\FileFinder\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Automation\FileFinder\dist\dockie_ui.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Automation\FileFinder\dist\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Automation\FileFinder\dist\screen_retriever_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Automation\FileFinder\dist\sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Automation\FileFinder\dist\sqlite3_flutter_libs_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Automation\FileFinder\dist\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Automation\FileFinder\dist\native_assets.json"; DestDir: "{app}"; Flags: ignoreversion
; The Flutter engine resolves its assets (flutter_assets, app.so, icudtl.dat)
; relative to <exe dir>\data\, so the data folder must keep its subfolder.
; A bare "dist\data\*" -> "{app}" would install these files FLAT and make
; dockie_ui.exe crash instantly on launch.
Source: "D:\Projects\Automation\FileFinder\dist\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Auto-restart after install AND after a silent auto-update (no skipifsilent).
; runasoriginaluser launches the app in the user's normal (non-elevated)
; context instead of the elevated installer token — launching elevated is what
; produced the security/validation error during updates.
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall runasoriginaluser

